tabs:
    fields:
        color_section_primary:
            label: 'Primary'
            type: section
            span: full
            tab: 'Colors'
        color_primary:
            label: Primary
            type: colorpicker
            tab: 'Colors'
        color_primary_hover:
            label: Primary Hover
            type: colorpicker
            tab: 'Colors'
        color_primary_focus:
            label: Primary Focus
            type: colorpicker
            tab: 'Colors'
        color_on_primary_container:
            label: On Primary Container
            type: colorpicker
            tab: 'Colors'
        color_section_surface:
            label: 'Surface'
            type: section
            span: full
            tab: 'Colors'
        color_surface_dim:
            label: Surface Dim
            type: colorpicker
            tab: 'Colors'
        color_surface_container:
            label: Surface Container
            type: colorpicker
            tab: 'Colors'
        color_on_surface:
            label: On Surface
            type: colorpicker
            tab: 'Colors'
        color_on_surface_variant:
            label: On Surface Variant
            type: colorpicker
            tab: 'Colors'
        color_section_outline:
            label: 'Outline'
            type: section
            span: full
            tab: 'Colors'
        color_outline:
            label: Outline
            type: colorpicker
            tab: 'Colors'
        color_outline_variant:
            label: Outline Variant
            type: colorpicker
            tab: 'Colors'
